ALTER TABLE sale ADD COLUMN tax_amount TEXT NOT NULL DEFAULT '0';
ALTER TABLE sale ADD COLUMN discount_amount TEXT NOT NULL DEFAULT '0';
ALTER TABLE sale ADD COLUMN iva_rate REAL NOT NULL DEFAULT 16.0;
ALTER TABLE invoice ADD COLUMN tax_amount TEXT NOT NULL DEFAULT '0';
